# HW 4: Logistic Regression

## Importing libraries

In [0]:
from sklearn.linear_model import LogisticRegression
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

## Loading Dataset

In [0]:
# Load Iris dataset and find out what is in this dataset
iris = datasets.load_iris()
for key, value in iris.items():
    print(key)

data
target
target_names
DESCR
feature_names
filename


In [0]:
#what's in each of 
# target_names
# DESCR
# target
# feature_names
# data
# DESCR and target are shown below. 
# Continue to work out the rest by appending more cells below.
print(iris.target_names)
print(iris.data)
print(iris.feature_names)
print(iris.filename)


['setosa' 'versicolor' 'virginica']
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 

In [0]:
#Let's see the description of this dataset?
iris['DESCR']

'.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ============== ==== =

In [0]:
#What's in target?
iris['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [0]:
#How many 0s, 1s, and 2s are in target?

## Using Logistic Regression for binary class classification

In [0]:
# Let's focus on data with only two classes ( the first 100 entries)
data_100 = iris.data[:100,:]
target_100 = iris.target[:100]

In [0]:
#check the size of data_100

## Standardize Features

In [0]:
#What's the mean and standard deviation of data_100 and target_100


In [0]:
scaler = StandardScaler()
# Transform the feature
data_100_standardized = scaler.fit_transform(data_100)

In [0]:
#what's the mean and standard deviation of the standardized data_100


## Create Logistic Regression

In [0]:
#Let's create a dataframe table to store all the features
features = pd.DataFrame(data_100_standardized, columns=iris.feature_names)
features.head()

In [0]:
#Create another dataframe to store the target
target = pd.DataFrame(target_100, columns=['target'])

In [0]:
# let's combine these two 'tables' into one dataframe
df = pd.concat([features,target], axis=1)
df.head(2)

In [0]:
#find out which is most correlated to the target?


In [0]:
# Create logistic regression object
LogReg = LogisticRegression()

## Train Logistic Regression

In [0]:
#Create (X,y) data pair ready for fitting the model
X = df[iris.feature_names]
y=df['target']

In [0]:
# Train model using the entire dataset


In [0]:
# Add a column predictions to the df datagrame on the predicted values based on X


In [0]:
#What's the score of using the entire dataset to train our Logistic Regression?


In [0]:
# probability of each class as validated against X

In [0]:
# Plot the predicted probabilities of petal length (cm) against predictions


##  Multi-class classification using Logistic Regression

In [0]:
#Load Iris dataset again
iris = datasets.load_iris()

In [0]:
#Standardize the dataset
scaler2 = StandardScaler()

# Transform the feature
standardized_data = scaler2.fit_transform(iris.data)

In [0]:
#create dataframes for data and target separately
data = pd.DataFrame(standardized_data, columns=iris.feature_names)
target = pd.DataFrame(iris.target, columns=['target'])

In [0]:
#Combine data and target into one big dataframe tables


In [0]:
#check how many different values does target have?


In [0]:
#Create a new copy of Logistic Regression class
LogRegM = LogisticRegression()

In [0]:
#Define (X,y) to be used for training the model
X=df[iris.feature_names]
y=df['target']

In [0]:
#Fit the model with all the data
#Find out how well it scores


In [0]:
#Show which ones (rows) the model fail to predict 


In [0]:
#Show the predict_proba of those (rows) that failed to predict correctly.
#Is the probability of the target class close/not close to that of the predicted class in these cases?
